// <auto-generated />
using System;
using JeffShared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JeffShared.Migrations
{
    [DbContext(typeof(LocationContext))]
    [Migration("20190427124849_AddedAlbumClassFinal4")]
    partial class AddedAlbumClassFinal4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JeffShared.ViewModel.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Band");

                    b.Property<string>("FileName");

                    b.Property<string>("Name");

                    b.Property<string>("Review");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("JeffShared.ViewModel.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<string>("Description");

                    b.Property<bool>("Important");

                    b.HasKey("Id");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("JeffShared.ViewModel.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("JeffShared.ViewModel.MemberAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId");

                    b.Property<int>("MemberId");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberAlbum");
                });

            modelBuilder.Entity("JeffShared.ViewModel.MemberAlbum", b =>
                {
                    b.HasOne("JeffShared.ViewModel.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JeffShared.ViewModel.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
